apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: avtchat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avtchat-frontend
  template:
    metadata:
      labels:
        app: avtchat-frontend
    spec:
      containers:
        - name: avtchat-frontend
          env:
            - name: PORT
              value: "8000"
          image: registry.dev.dxr.kr/avtchat/frontend:0.0.1.1700421712
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: avtchat-frontend
spec:
  selector:
    app: avtchat-frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: demo
  name: avtchat-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - avatar-chat.dev.dxr.kr
      secretName: avtchat-ingress-tls
  rules:
    - host: avatar-chat.dev.dxr.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avtchat-frontend
                port:
                  number: 8000
